Resources:
  ConfigRuleEC2StackSet:
    Type: PGE::CloudFormation::StackSet
    Properties:
      PermissionModel: SERVICE_MANAGED
      TemplateURL: https://cf-templates-681v3yr6sl6i-us-west-2.s3-us-west-2.amazonaws.com/ec2-config.yml
      StackInstancesGroup: 
        - Regions:
            # - us-east-1
            - us-west-2
          DeploymentTargets:
            OrganizationalUnitIds:
              - ou-nfqe-bfrwogtk
      Tags:
        - Key: AppID
          Value: APP-2772
        - Key: Owner
          Value: tahv
Outputs:
  StackSetId:
    Value: !Ref ConfigRuleEC2StackSet