AWSTemplateFormatVersion: "2010-09-09"
Description: "PGE SAF2.0 across organization wait handle StackSet."
Parameters:
  pPgeStackSetName:
    Description: Basename of the StackSet and instances
    Type: String
    Default: cscoe-wh-test
  pPgeAppId:
    Description: "AMPS Id"
    Type: String
    Default: APP-2772
    AllowedPattern: ^[A-Za-z0-9_.:/=+@\- ]{0,256}$
  pPgeEnv:
    Description: "Operating environment"
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/general/environment"
  pPgeOwner:
    Description: "System or Asset Owner"
    Type: String
    Default: nack c1kp j9ge d2wr
    AllowedPattern: ^[A-Za-z0-9_.:/=+@\- ]{0,256}$
  pPgeNotify:
    Description: "Notification for system failure & maintenance"
    Type: String
    Default: CYBERSECURITYServicesCloudSecurityEmployees@pge.com
    AllowedPattern: ^[A-Za-z0-9_.:/=+@\- ]{0,256}$
  pPgeLambdaS3Bucket:
    Description: "S3 Bucket for Lambda zip file"
    Type: String
    AllowedPattern: ^[A-Za-z0-9_.:/=+@\- ]{0,256}$
    Default: cf-templates-681v3yr6sl6i-us-west-2
  pPgeOrganizationUnit:
    Description: "Deploying to this target OU."
    Type: String
    AllowedPattern: ^[A-Za-z0-9_.:/=+@\- ]{0,256}$
    Default: ou-nfqe-9zjup0sq
Resources:
  cscoeWaitHandleStackSet:
    Type: PGE::CloudFormation::StackSet
    Properties:
      StackSetName: !Ref pPgeStackSetName
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: True
        RetainStacksOnAccountRemoval: False
      TemplateBody: |
        {
          "AWSTemplateFormatVersion": "2010-09-09",
          "Parameters": {
            "pPgeLambdaS3Bucket": {
              "Type": "String"
            }
          },
          "Resources": {
            "IntegrationTestWaitHandle": {
              "Type": "AWS::CloudFormation::WaitConditionHandle",
              "Properties": {}
            }
          }
        }
      StackInstancesGroup:
        - Regions:
            # - us-east-1
            - us-west-2
          DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref pPgeOrganizationUnit
      Parameters:
        - ParameterKey: pPgeLambdaS3Bucket
          ParameterValue: !Ref pPgeLambdaS3Bucket
      Tags:
        - Key: "AppID"
          Value: !Ref pPgeAppId
        - Key: "Environment"
          Value: !Ref pPgeEnv
        - Key: "Owner"
          Value: !Ref pPgeOwner
        - Key: "Compliance"
          Value: "None"
        - Key: "Notify"
          Value: !Ref pPgeNotify
        - Key: "DataClassification"
          Value: "Internal"
        - Key: "BusinessImpact"
          Value: "No Impact"
        - Key: "CatalogProvision"
          Value: "No"
        - Key: "TrustLevel"
          Value: "NA"
        - Key: "MCP"
          Value: "No MCP"
Outputs:
  StackSetId:
    Value: !Ref cscoeWaitHandleStackSet
